#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xAB4655A126D292E4 (coreteam@netfilter.org)
#
Name     : nftables
Version  : 0.9.2
Release  : 21
URL      : http://netfilter.org/projects/nftables/files/nftables-0.9.2.tar.bz2
Source0  : http://netfilter.org/projects/nftables/files/nftables-0.9.2.tar.bz2
Source1 : http://netfilter.org/projects/nftables/files/nftables-0.9.2.tar.bz2.sig
Summary  : Netfilter tables userspace tools
Group    : Development/Tools
License  : GPL-2.0
Requires: nftables-bin = %{version}-%{release}
Requires: nftables-lib = %{version}-%{release}
Requires: nftables-license = %{version}-%{release}
Requires: nftables-python = %{version}-%{release}
Requires: nftables-python3 = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-distutils3
BuildRequires : docbook-utils
BuildRequires : flex
BuildRequires : gmp-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(libmnl)
BuildRequires : pkgconfig(libnftnl)
BuildRequires : pkgconfig(xtables)
BuildRequires : readline-dev
BuildRequires : sed

%description
No detailed description available

%package bin
Summary: bin components for the nftables package.
Group: Binaries
Requires: nftables-license = %{version}-%{release}

%description bin
bin components for the nftables package.


%package dev
Summary: dev components for the nftables package.
Group: Development
Requires: nftables-lib = %{version}-%{release}
Requires: nftables-bin = %{version}-%{release}
Provides: nftables-devel = %{version}-%{release}
Requires: nftables = %{version}-%{release}
Requires: nftables = %{version}-%{release}

%description dev
dev components for the nftables package.


%package lib
Summary: lib components for the nftables package.
Group: Libraries
Requires: nftables-license = %{version}-%{release}

%description lib
lib components for the nftables package.


%package license
Summary: license components for the nftables package.
Group: Default

%description license
license components for the nftables package.


%package python
Summary: python components for the nftables package.
Group: Default
Requires: nftables-python3 = %{version}-%{release}

%description python
python components for the nftables package.


%package python3
Summary: python3 components for the nftables package.
Group: Default
Requires: python3-core

%description python3
python3 components for the nftables package.


%prep
%setup -q -n nftables-0.9.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567968309
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --disable-man-doc
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1567968309
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nftables
cp COPYING %{buildroot}/usr/share/package-licenses/nftables/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nft

%files dev
%defattr(-,root,root,-)
/usr/include/nftables/libnftables.h
/usr/lib64/libnftables.so
/usr/lib64/pkgconfig/libnftables.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnftables.so.1
/usr/lib64/libnftables.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nftables/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
