#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xAB4655A126D292E4 (coreteam@netfilter.org)
#
Name     : nftables
Version  : 0.8
Release  : 13
URL      : http://netfilter.org/projects/nftables/files/nftables-0.8.tar.bz2
Source0  : http://netfilter.org/projects/nftables/files/nftables-0.8.tar.bz2
Source99 : http://netfilter.org/projects/nftables/files/nftables-0.8.tar.bz2.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: nftables-bin
BuildRequires : bison
BuildRequires : flex
BuildRequires : gmp-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(libmnl)
BuildRequires : pkgconfig(libnftnl)
BuildRequires : pkgconfig(xtables)
BuildRequires : readline-dev
BuildRequires : sed

%description
This test-suite is intended to perform tests of higher level than
the other reggresion test-suite.

%package bin
Summary: bin components for the nftables package.
Group: Binaries

%description bin
bin components for the nftables package.


%prep
%setup -q -n nftables-0.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1511140897
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1511140897
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nft
